config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :recipes
  resources :cuisines
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
    has_many :recipes

    validates :name, presence: { message: 'Você deve informar o nome da cozinha' }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :cuisine 

    validates :title, :recipe_type, :cuisine_id, :difficulty, :cook_time, :ingredients, :cook_method, presence: { message: 'Você deve informar todos os dados da receita' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController

    def show 
        @cuisine = Cuisine.find(params[:id])
        @recipes = @cuisine.recipes
    end

    def new
        @cuisine = Cuisine.new()
    end

    def create
        @cuisine = Cuisine.new(params.require(:cuisine).permit(:name))
        if @cuisine.save
        flash[:notice] = 'Cozinha cadastrada com sucesso'
        redirect_to cuisine_path(@cuisine)
        else
        flash[:alert] = 'Não foi possível cadastar a cozinha'
        render 'new'
        end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @recipes = Recipe.all
        @cuisines = Cuisine.all
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def show
        @recipe = Recipe.find(params[:id])
    end


    def new
        @recipe = Recipe.new()
        @cuisines = Cuisine.all
    end

    def create
        @cuisines = Cuisine.all
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            flash[:notice] = 'Receita cadastrada com sucesso'
            redirect_to recipe_path(@recipe)
        else
            flash[:alert] = 'Não foi possível cadastrar a receita'
            render 'new'
        end
    end

    private
    def recipe_params
        params.require(:recipe).permit(:title, :recipe_type, :cuisine_id, :difficulty, :cook_time, :ingredients, :cook_method)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisines/new.html.erb
<h1>Cadastro de Cozinhas</h1>
<p><%= alert %></p>

<% @cuisine.errors.full_messages.each do |erro| %>
    <p><%= erro %></p>
<% end %>


<%= form_for @cuisine do |f| %>

    <div>
      <%= f.label :name, "Nome" %>
      <%= f.text_field :name %>
    </div>

    <div>
    <%= f.submit 'Enviar' %>
    </div>
<% end %>

app/views/cuisines/show.html.erb
<h1><%= @cuisine.name %></h1>

<p><%= notice %></p>
<% if @recipes.present? %>
    <%= @recipes.each do |r| %>
        <h1><%= r.title %></h1>
        <li><%= r.recipe_type %></li>
        <li><%= r.difficulty %></li>
        <li><%= r.cook_time %> minutos</li>
    <% end %>
<% else %>
Nenhuma receita encontrada para este tipo de cozinha
<% end %>

app/views/home/index.html.erb
<h1>CookBook</h1>

<p>Bem-vindo ao maior livro de receitas online</p>

<p><%= link_to('Enviar uma receita', new_recipe_path) %></p>

<h2>Receitas por cozinha</h2>
<% @cuisines.each do |c| %>
    <li><%= link_to(c.name, c) %></li>
<% end %>

<% @recipes.each do |r| %>
    <h1><%= link_to(r.title, r) %></h1>
    <li><%= r.recipe_type %></li>
    <li><%= r.cuisine.name %></li>
    <li><%= r.difficulty %></li>
    <li><%= r.cook_time %> minutos</li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookBookLili</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/new.html.erb
<h1>Cadastro de novas receitas </h1>
<p><%= alert %></p>
<% @recipe.errors.full_messages.each do |erro| %>
  <p><%= erro %></p>
<% end %>

<%= form_for @recipe, html: { multipart: true } do |f| %>
    <div>
      <%= f.label :title, "Título" %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :recipe_type, "Tipo da Receita" %>
      <%= f.text_field :recipe_type %>
    </div>
    <div>
      <%= f.label :cuisine_id, "Cozinha" %>
      <%= f.collection_select(:cuisine_id, @cuisines, :id, :name) %>
    </div>
    <div>
      <%= f.label :difficulty, "Dificuldade" %>
      <%= f.text_field :difficulty %>
    </div>
    <div>
      <%= f.label :cook_time, "Tempo de Preparo" %>
      <%= f.text_field :cook_time %>
    </div>
    <div>
      <%= f.label :ingredients, "Ingredientes" %>
      <%= f.text_field :ingredients %>
    </div>
    <div>
      <%= f.label :cook_method, "Como Preparar" %>
      <%= f.text_field :cook_method %>
    </div>
    <div>
      <%= f.submit 'Enviar' %>
    </div>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<p><%= notice %></p> 
<h3>Detalhes</h3>
<p><%= @recipe.recipe_type %></p>
<p><%= @recipe.cuisine.name %></p>
<p><%= @recipe.difficulty %></p>
<p><%= @recipe.cook_time %> minutos</p>
<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %></p>
<h3>Como Preparar</h3>
<p><%= @recipe.cook_method %></p>
<p><%= link_to('Voltar', root_path) %></p>